// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.8.0.0
//      SpecFlow Generator Version:3.8.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NLSpecPlay.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.8.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class YahooFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private string[] _featureTags = new string[] {
                "Yahoo"};
        
#line 1 "Yahoo.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Yahoo", "\tSimple checking Yahoo using Chrome", ProgrammingLanguage.CSharp, new string[] {
                        "Yahoo"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Yahoo")))
            {
                global::NLSpecPlay.Features.YahooFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CheckIfTitleOrImgHasChanged(string title, string img, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Title", title);
            argumentsOfScenario.Add("Img", img);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check if title or img has changed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.When("user check the web", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
 testRunner.Then(string.Format("the title should be {0}", title), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 8
 testRunner.And(string.Format("the img url should be {0}", img), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Check if title or img has changed: Hacker tìm ra bằng chứng \'tuyệt mật\' liên quan" +
            " vụ 13 tỷ, giúp bà Phương Hằng tung \'đòn chí mạng\', gây náo l.o.ạ.n showbiz Việt" +
            " vài ngày qua là ai?")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Yahoo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Yahoo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Hacker tìm ra bằng chứng \'tuyệt mật\' liên quan vụ 13 tỷ, giúp bà Phương Hằng tung" +
            " \'đòn chí mạng\', gây náo l.o.ạ.n showbiz Việt vài ngày qua là ai?")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Title", "Hacker tìm ra bằng chứng \'tuyệt mật\' liên quan vụ 13 tỷ, giúp bà Phương Hằng tung" +
            " \'đòn chí mạng\', gây náo l.o.ạ.n showbiz Việt vài ngày qua là ai?")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Img", "https://s.yimg.com/uu/api/res/1.2/D7oADB6LVIfwIq1Xkc.pyw--~B/Zmk9c3RyaW07aD0yNDY7" +
            "cT04MDt3PTQ0MDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/am/60d/146463abb3d7332b1" +
            "7d49121d07cafbb.cf.webp")]
        public virtual void CheckIfTitleOrImgHasChanged_HackerTimRaBằngChứngTuyệtMậtLienQuanVụ13TỷGiupBaPhươngHằngTungDonChiMạngGayNaoL_O_Ạ_NShowbizViệtVaiNgayQuaLaAi()
        {
#line 5
this.CheckIfTitleOrImgHasChanged("Hacker tìm ra bằng chứng \'tuyệt mật\' liên quan vụ 13 tỷ, giúp bà Phương Hằng tung" +
                    " \'đòn chí mạng\', gây náo l.o.ạ.n showbiz Việt vài ngày qua là ai?", "https://s.yimg.com/uu/api/res/1.2/D7oADB6LVIfwIq1Xkc.pyw--~B/Zmk9c3RyaW07aD0yNDY7" +
                    "cT04MDt3PTQ0MDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/am/60d/146463abb3d7332b1" +
                    "7d49121d07cafbb.cf.webp", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Check if title or img has changed: Anh trai tôi ly hôn vì vợ vô sinh, 4 năm sau c" +
            "hị dâu cũ về quê đi ngang qua cửa nhà mà khiến cả gia đình tôi \'hóa đá\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Yahoo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Yahoo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Anh trai tôi ly hôn vì vợ vô sinh, 4 năm sau chị dâu cũ về quê đi ngang qua cửa n" +
            "hà mà khiến cả gia đình tôi \'hóa đá\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Title", "Anh trai tôi ly hôn vì vợ vô sinh, 4 năm sau chị dâu cũ về quê đi ngang qua cửa n" +
            "hà mà khiến cả gia đình tôi \'hóa đá\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Img", "https://s.yimg.com/uu/api/res/1.2/0.UdsmSorXcRQPrJZsBruQ--~B/Zmk9c3RyaW07aD0yNDY7" +
            "cT04MDt3PTQ0MDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/am/60d/84d814fbb819314f7" +
            "a9b34179e8fb4b1.cf.webp")]
        public virtual void CheckIfTitleOrImgHasChanged_AnhTraiToiLyHonViVợVoSinh4NamSauChịDauCũVềQueDiNgangQuaCửaNhaMaKhiếnCảGiaDinhToiHoaDa()
        {
#line 5
this.CheckIfTitleOrImgHasChanged("Anh trai tôi ly hôn vì vợ vô sinh, 4 năm sau chị dâu cũ về quê đi ngang qua cửa n" +
                    "hà mà khiến cả gia đình tôi \'hóa đá\'", "https://s.yimg.com/uu/api/res/1.2/0.UdsmSorXcRQPrJZsBruQ--~B/Zmk9c3RyaW07aD0yNDY7" +
                    "cT04MDt3PTQ0MDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/am/60d/84d814fbb819314f7" +
                    "a9b34179e8fb4b1.cf.webp", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Check if title or img has changed: Đam mê trò chơi \'đổi vợ đổi chồng\', người đàn " +
            "ông ra sức thuyết phục vợ nhập hội và nhận cái kết cay đắng")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Yahoo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Yahoo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Đam mê trò chơi \'đổi vợ đổi chồng\', người đàn ông ra sức thuyết phục vợ nhập hội " +
            "và nhận cái kết cay đắng")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Title", "Đam mê trò chơi \'đổi vợ đổi chồng\', người đàn ông ra sức thuyết phục vợ nhập hội " +
            "và nhận cái kết cay đắng")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Img", "https://s.yimg.com/uu/api/res/1.2/fFwki7neqrZ1LV7jzak__A--~B/Zmk9c3RyaW07aD0yNDY7" +
            "cT04MDt3PTQ0MDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/am/60d/ce669a025edd077d8" +
            "606537a9eaa8a4b.cf.webp")]
        public virtual void CheckIfTitleOrImgHasChanged_DamMeTroChơiDổiVợDổiChồngNgườiDanOngRaSứcThuyếtPhụcVợNhậpHộiVaNhậnCaiKếtCayDắng()
        {
#line 5
this.CheckIfTitleOrImgHasChanged("Đam mê trò chơi \'đổi vợ đổi chồng\', người đàn ông ra sức thuyết phục vợ nhập hội " +
                    "và nhận cái kết cay đắng", "https://s.yimg.com/uu/api/res/1.2/fFwki7neqrZ1LV7jzak__A--~B/Zmk9c3RyaW07aD0yNDY7" +
                    "cT04MDt3PTQ0MDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/am/60d/ce669a025edd077d8" +
                    "606537a9eaa8a4b.cf.webp", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
